---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #- name: ubuntu-16.04
   # driver:
      #platform: debian
 # - name: ubuntu-14.04
 # - name: centos-6.9
  - name: centos-7
    driver:
      platform: rhel
      run_command: /usr/lib/systemd/systemd

suites:
  - name: SystemD
    run_list:
      - recipe[ARR::systemd]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
